package hermes.gui.dialogs;

import com.hermes.client.HCUser;
import com.hermes.common.HUser;
import com.hermes.common.constants.HBrowsable;
import com.hermes.common.constants.HGender;
import com.hermes.common.constants.HLineType;
import com.hermes.common.constants.HLocation;
import hermes.util.ConfigReader;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.lang.reflect.Field;
import java.net.InetAddress;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jomartinez
 */
public class ConfigDialog extends javax.swing.JDialog
{

    /**
     * Creates new form ConfigDialog
     */
    private JOptionPane optionPane;
    private HCUser user;
    private String avatarPath;
    
    public ConfigDialog(HUser user, java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        getRootPane().setBorder(javax.swing.BorderFactory.createLineBorder(new Color(179,179,179)));
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        optionPane = new JOptionPane();
        LAvatar.setIcon(user.getAvatar());
        TFUsername.setText(user.getUsername());
        CBCountry.setSelectedItem(user.getCountry());
        TFRegion.setText(user.getRegion());
        SAge.setValue(user.getAge());
        CBGender.setSelectedItem(user.getGender());
        TFPersonalMessage.setText(user.getPersonalMessage());
        CBBrowsable.setSelected(user.getBrowsable() == HBrowsable.Browsable || user.getBrowsable() == HBrowsable.Browsable_and_support_compress);
        CBLLineType.setSelectedItem(user.getLinetype());
        SShared.setValue(user.getFilecount());
        SPort.setValue(user.getDataport());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSeparator1 = new javax.swing.JSeparator();
        LAvatar = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        TFUsername = new javax.swing.JTextField();
        LCountry = new javax.swing.JLabel();
        CBCountry = new javax.swing.JComboBox(HLocation.values());
        LRegion = new javax.swing.JLabel();
        TFRegion = new javax.swing.JTextField();
        LAge = new javax.swing.JLabel();
        SAge = new javax.swing.JSpinner();
        LGender = new javax.swing.JLabel();
        CBGender = new javax.swing.JComboBox(HGender.values());
        LPersonalmessage = new javax.swing.JLabel();
        TFPersonalMessage = new javax.swing.JTextField();
        CBBrowsable = new javax.swing.JCheckBox();
        LLineType = new javax.swing.JLabel();
        CBLLineType = new javax.swing.JComboBox(HLineType.values());
        LSharedCount = new javax.swing.JLabel();
        SShared = new javax.swing.JSpinner();
        LPort = new javax.swing.JLabel();
        final SpinnerNumberModel smPort = new SpinnerNumberModel(((short)0),((short)0),Short.MAX_VALUE,((short)1));
        SPort = new javax.swing.JSpinner();
        BAcept = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        BClear = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(310, 411));
        setMinimumSize(new java.awt.Dimension(310, 411));

        LAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LAvatar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LAvatarMouseClicked(evt);
            }
        });

        LUsername.setText("Username:");

        TFUsername.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LCountry.setText("Country:");

        CBCountry.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LRegion.setText("Region:");

        TFRegion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LAge.setText("Age:");

        SAge.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        SAge.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)100), Byte.valueOf((byte)1)));

        LGender.setText("Gender:");

        CBGender.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LPersonalmessage.setText("Personal Message:");

        TFPersonalMessage.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        CBBrowsable.setText("Browsable:            ");
        CBBrowsable.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CBBrowsable.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CBBrowsableActionPerformed(evt);
            }
        });

        LLineType.setText("Line Type:");

        CBLLineType.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LSharedCount.setText("Shared Count:");

        final SpinnerNumberModel countSpinnerModel = new SpinnerNumberModel(((short)0),((short)0),Short.MAX_VALUE,((short)1));
        SShared.setModel(countSpinnerModel);
        SShared.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        LPort.setText("Port:");

        SPort.setModel(smPort);
        SPort.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        BAcept.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BAcept.setText("Acept");
        BAcept.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BAceptActionPerformed(evt);
            }
        });

        BCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/close.png"))); // NOI18N
        BCancel.setBorderPainted(false);
        BCancel.setContentAreaFilled(false);
        BCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/close-over.png"))); // NOI18N
        BCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BCancelActionPerformed(evt);
            }
        });

        BClear.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        BClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/remove.png"))); // NOI18N
        BClear.setBorderPainted(false);
        BClear.setContentAreaFilled(false);
        BClear.setMaximumSize(new java.awt.Dimension(20, 20));
        BClear.setMinimumSize(new java.awt.Dimension(20, 20));
        BClear.setPreferredSize(new java.awt.Dimension(20, 20));
        BClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(CBBrowsable)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LAge)
                                            .addComponent(LGender)
                                            .addComponent(LPersonalmessage)
                                            .addComponent(LRegion)
                                            .addComponent(LCountry))
                                        .addComponent(LLineType, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(LUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFPersonalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFUsername)
                                        .addComponent(CBCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TFRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LSharedCount)
                            .addComponent(LPort))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBLLineType, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SShared, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(SPort))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BAcept)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(LAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LUsername)
                    .addComponent(TFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCountry)
                    .addComponent(CBCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRegion)
                    .addComponent(TFRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAge)
                    .addComponent(SAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LGender))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFPersonalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPersonalmessage))
                .addGap(10, 10, 10)
                .addComponent(CBBrowsable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBLLineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LLineType))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LSharedCount)
                            .addComponent(SShared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPort)
                            .addComponent(SPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BAcept)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BCancelActionPerformed
    {//GEN-HEADEREND:event_BCancelActionPerformed
        optionPane.setValue(new Integer(JOptionPane.CLOSED_OPTION));
        dispose();
    }//GEN-LAST:event_BCancelActionPerformed

    private void LAvatarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LAvatarMouseClicked
    {//GEN-HEADEREND:event_LAvatarMouseClicked
        JFileChooser fc = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fc.setFileFilter(imageFilter);
        int res = fc.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION)
        {
            LAvatar.setIcon(new ImageIcon(fc.getSelectedFile().getAbsolutePath()));
        }
    }//GEN-LAST:event_LAvatarMouseClicked

    private void BAceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BAceptActionPerformed
    {//GEN-HEADEREND:event_BAceptActionPerformed

        HBrowsable broswable = HBrowsable.Not_Browsable;
        if (CBBrowsable.isSelected())
        {
            broswable = HBrowsable.Browsable;
        }
        Random rnd = new Random();

        byte[] bPublicIp = new byte[4];
        byte[] bPrivateIp = new byte[4];
        byte[] bNodeIp = new byte[4];
        byte[] bUploaded = new byte[3];

        rnd.nextBytes(bPublicIp);
        rnd.nextBytes(bPrivateIp);
        rnd.nextBytes(bNodeIp);
        rnd.nextBytes(bUploaded);
        
        try
        {
            user = new HCUser(TFUsername.getText(), Short.parseShort(SShared.getValue() + ""), (HLineType) CBLLineType.getSelectedItem(), broswable, (Byte) SAge.getValue(), (HGender) CBGender.getSelectedItem(), (HLocation) CBCountry.getSelectedItem(), TFRegion.getText(), InetAddress.getByAddress(bPublicIp), Short.parseShort(SPort.getValue() + ""), InetAddress.getByAddress(bPrivateIp), InetAddress.getByAddress(bNodeIp),(short)rnd.nextInt(), bUploaded[0],bUploaded[1],bUploaded[2]);
            user.setPersonalMessage(TFPersonalMessage.getText());
            user.setAvatar((ImageIcon) LAvatar.getIcon());
            ConfigReader.getInstance().save(user);
        }
        catch (IOException ex)
        {
            Logger.getLogger(ConfigDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NoSuchAlgorithmException ex)
        {
            Logger.getLogger(ConfigDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        optionPane.setValue(new Integer(JOptionPane.YES_OPTION));
        dispose();
    }//GEN-LAST:event_BAceptActionPerformed

    private void BClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BClearActionPerformed
    {//GEN-HEADEREND:event_BClearActionPerformed
        LAvatar.setIcon(null);
    }//GEN-LAST:event_BClearActionPerformed

    private void CBBrowsableActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CBBrowsableActionPerformed
    {//GEN-HEADEREND:event_CBBrowsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBrowsableActionPerformed

    public int getOption()
    {
        return (int) optionPane.getValue();
    }

    public HCUser getUser()
    {
        return user;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAcept;
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BClear;
    private javax.swing.JCheckBox CBBrowsable;
    private javax.swing.JComboBox CBCountry;
    private javax.swing.JComboBox CBGender;
    private javax.swing.JComboBox CBLLineType;
    private javax.swing.JLabel LAge;
    private javax.swing.JLabel LAvatar;
    private javax.swing.JLabel LCountry;
    private javax.swing.JLabel LGender;
    private javax.swing.JLabel LLineType;
    private javax.swing.JLabel LPersonalmessage;
    private javax.swing.JLabel LPort;
    private javax.swing.JLabel LRegion;
    private javax.swing.JLabel LSharedCount;
    private javax.swing.JLabel LUsername;
    private javax.swing.JSpinner SAge;
    private javax.swing.JSpinner SPort;
    private javax.swing.JSpinner SShared;
    private javax.swing.JTextField TFPersonalMessage;
    private javax.swing.JTextField TFRegion;
    private javax.swing.JTextField TFUsername;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
