/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hermes.gui.dialogs;

import com.hermes.common.HChannel;
import com.hermes.common.HHash;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;

/**
 *
 * @author joaquin
 */
public class HashDialog extends javax.swing.JDialog
{

    /**
     * Creates new form HashDialog
     */
     public static final int         ACEPT_OPTION = 0;
    public static final int         CANCEL_OPTION = 2;
    
    private int closeOption;
    private HChannel channel;
    
    public HashDialog(java.awt.Frame parent, boolean modal,String defaultHash)
    {
        super(parent, modal);
        initComponents();        
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
         getRootPane().setBorder(javax.swing.BorderFactory.createLineBorder(new Color(179,179,179)));
        TAHash.setText(defaultHash);
        KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
        Action actionListener = new AbstractAction()
        {
            public void actionPerformed(ActionEvent actionEvent)
            {
                BCloseActionPerformed(new ActionEvent(this, 12, ""));
            }
        };
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ESCAPE");
        rootPane.getActionMap().put("ESCAPE", actionListener);
        TAHash.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        TAHash = new javax.swing.JTextArea();
        BConnect = new javax.swing.JButton();
        LTitle = new javax.swing.JLabel();
        BClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(269, 175));
        setMinimumSize(new java.awt.Dimension(269, 175));
        setResizable(false);

        TAHash.setColumns(20);
        TAHash.setLineWrap(true);
        TAHash.setRows(5);
        jScrollPane1.setViewportView(TAHash);

        BConnect.setText("Connect");
        BConnect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BConnectActionPerformed(evt);
            }
        });

        LTitle.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        LTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTitle.setText("Connecting to Channel");

        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/close.png"))); // NOI18N
        BClose.setBorderPainted(false);
        BClose.setContentAreaFilled(false);
        BClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/close-over.png"))); // NOI18N
        BClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(BClose, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(LTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(BConnect)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BClose, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTitle)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BConnect)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BCloseActionPerformed
    {//GEN-HEADEREND:event_BCloseActionPerformed
        closeOption=CANCEL_OPTION;
        dispose();
    }//GEN-LAST:event_BCloseActionPerformed

    private void BConnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BConnectActionPerformed
    {//GEN-HEADEREND:event_BConnectActionPerformed
        String hash=TAHash.getText();
        
       
        try
        {
            channel=  HHash.getInstance().decode(hash);
            closeOption=ACEPT_OPTION;
            dispose();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Invalid Hash, Plese rewrite it.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BConnectActionPerformed

    public HChannel getChannel()
    {
        return channel;
    }

    public int getCloseOption()
    {
        return closeOption;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClose;
    private javax.swing.JButton BConnect;
    private javax.swing.JLabel LTitle;
    private javax.swing.JTextArea TAHash;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
