/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hermes.gui;

import com.hermes.common.AresFormater;
import javax.swing.JButton;

/**
 *
 * @author jomartinez
 */
public class ColorDialog extends javax.swing.JDialog
{

    /**
     * Creates new form ColorDialog
     */
    public ColorDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setUndecorated(modal);
        setSize(120,120);
        JButton bColor;
        for(int i=0;i<AresFormater.COLORS.length;i++)
        {
            bColor=new JButton();
            bColor.setSize(30,30);
            bColor.setBorderPainted(false);
            bColor.setContentAreaFilled(false);
            bColor.setOpaque(true);
            bColor.setBackground(AresFormater.COLORS[i]);
            add(bColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(4, 4));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
