package hermes.gui;

import com.hermes.client.HCUser;
import com.hermes.common.HUser;
import com.hermes.common.constants.HBrowsable;
import com.hermes.common.constants.HGender;
import com.hermes.common.constants.HLineType;
import com.hermes.common.constants.HLocation;
import hermes.util.ConfigReader;
import java.awt.Color;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jomartinez
 */
public class ConfigDialog extends javax.swing.JDialog
{

    /**
     * Creates new form ConfigDialog
     */
    private JOptionPane optionPane;
    private HCUser user;
    
    public ConfigDialog(HUser user,java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setSize(420, 355);
        
        optionPane=new JOptionPane();
        
        getRootPane().setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY.darker()));
        LAvatar.setIcon(user.getAvatar());
        TFUsername.setText(user.getUsername());
        CBCountry.setSelectedItem(user.getCountry());
        TFRegion.setText(user.getRegion());
        SAge.setValue(user.getAge());
        CBGender.setSelectedItem(user.getGender());
        TFPersonalMessage.setText(user.getPersonalMessage());
        CBBrowsable.setSelected(user.getBrowsable()==HBrowsable.Browsable ||user.getBrowsable()==HBrowsable.Browsable_and_support_compress );
        CBLLineType.setSelectedItem(user.getLinetype());
        SShared.setValue(user.getFilecount());
        SPort.setValue(user.getDataport());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        LAvatar = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        TFUsername = new javax.swing.JTextField();
        LCountry = new javax.swing.JLabel();
        CBCountry = new javax.swing.JComboBox(HLocation.values());
        LRegion = new javax.swing.JLabel();
        TFRegion = new javax.swing.JTextField();
        LAge = new javax.swing.JLabel();
        SAge = new javax.swing.JSpinner();
        LGender = new javax.swing.JLabel();
        CBGender = new javax.swing.JComboBox(HGender.values());
        LPersonalmessage = new javax.swing.JLabel();
        TFPersonalMessage = new javax.swing.JTextField();
        CBBrowsable = new javax.swing.JCheckBox();
        LLineType = new javax.swing.JLabel();
        CBLLineType = new javax.swing.JComboBox(HLineType.values());
        LSharedCount = new javax.swing.JLabel();
        SShared = new javax.swing.JSpinner();
        LPort = new javax.swing.JLabel();
        SPort = new javax.swing.JSpinner();
        BAcept = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LAvatar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                LAvatarMouseClicked(evt);
            }
        });

        LUsername.setText("Username:");

        LCountry.setText("Country:");

        LRegion.setText("Region:");

        LAge.setText("Age:");

        SAge.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)100), Byte.valueOf((byte)1)));

        LGender.setText("Gender:");

        LPersonalmessage.setText("Personal Message:");

        CBBrowsable.setText("Browsable:      ");
        CBBrowsable.setActionCommand("Browsable:");
        CBBrowsable.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LLineType.setText("Line Type:");

        LSharedCount.setText("Shared Count:");

        SShared.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), null, Short.valueOf((short)1)));

        LPort.setText("Port:");

        SPort.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), null, Short.valueOf((short)1)));

        BAcept.setText("Acept");
        BAcept.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BAceptActionPerformed(evt);
            }
        });

        BCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hermes/resources/images/close.png"))); // NOI18N
        BCancel.setBorderPainted(false);
        BCancel.setContentAreaFilled(false);
        BCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BAcept)
                    .addComponent(BCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LCountry)
                            .addComponent(LUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LRegion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(CBBrowsable))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LSharedCount)
                                .addComponent(LLineType)
                                .addComponent(LPort))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SShared, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CBLLineType, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SPort, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LGender)
                                    .addComponent(LAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SAge, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBGender, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LPersonalmessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFPersonalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LUsername))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCountry)))
                    .addComponent(LAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LRegion))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LAge))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LGender)
                    .addComponent(CBGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPersonalmessage)
                    .addComponent(TFPersonalMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBBrowsable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLineType)
                    .addComponent(CBLLineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSharedCount)
                    .addComponent(SShared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPort)
                    .addComponent(SPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(BAcept)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BCancelActionPerformed
    {//GEN-HEADEREND:event_BCancelActionPerformed
         optionPane.setValue(new Integer(JOptionPane.CLOSED_OPTION));
        dispose();
    }//GEN-LAST:event_BCancelActionPerformed

    private void LAvatarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LAvatarMouseClicked
    {//GEN-HEADEREND:event_LAvatarMouseClicked
        JFileChooser fc=new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fc.setFileFilter(imageFilter);
        int res=fc.showOpenDialog(this);
        
        if(res==JFileChooser.APPROVE_OPTION)
        {
            LAvatar.setIcon(new ImageIcon(fc.getSelectedFile().getAbsolutePath()));
        }
    }//GEN-LAST:event_LAvatarMouseClicked

    private void BAceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BAceptActionPerformed
    {//GEN-HEADEREND:event_BAceptActionPerformed
        
        HBrowsable broswable=HBrowsable.Not_Browsable;
        if(CBBrowsable.isSelected())
        {
            broswable=HBrowsable.Browsable;
        }

        user=new HCUser(TFUsername.getText(),(Short)SShared.getValue(),(HLineType)CBLLineType.getSelectedItem(),broswable,(byte)SAge.getValue(),(HGender)CBGender.getSelectedItem() ,(HLocation)CBCountry.getSelectedItem() ,null, null, (short)SPort.getValue(), null, null,(short) 0,(byte)0,(byte)0,(byte)0);
        user.setRegion(TFRegion.getText());
        user.setAvatar((ImageIcon) LAvatar.getIcon());
        try
        {
            ConfigReader.getInstance().save(user);
        } catch (IOException ex)
        {
            Logger.getLogger(ConfigDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex)
        {
            Logger.getLogger(ConfigDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        optionPane.setValue(new Integer(JOptionPane.YES_OPTION));
        dispose();
    }//GEN-LAST:event_BAceptActionPerformed

    
    public int getOption()
    {
        return (int)optionPane.getValue();
    }
    
    public HCUser getUser()
    {
        return user;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAcept;
    private javax.swing.JButton BCancel;
    private javax.swing.JCheckBox CBBrowsable;
    private javax.swing.JComboBox CBCountry;
    private javax.swing.JComboBox CBGender;
    private javax.swing.JComboBox CBLLineType;
    private javax.swing.JLabel LAge;
    private javax.swing.JLabel LAvatar;
    private javax.swing.JLabel LCountry;
    private javax.swing.JLabel LGender;
    private javax.swing.JLabel LLineType;
    private javax.swing.JLabel LPersonalmessage;
    private javax.swing.JLabel LPort;
    private javax.swing.JLabel LRegion;
    private javax.swing.JLabel LSharedCount;
    private javax.swing.JLabel LUsername;
    private javax.swing.JSpinner SAge;
    private javax.swing.JSpinner SPort;
    private javax.swing.JSpinner SShared;
    private javax.swing.JTextField TFPersonalMessage;
    private javax.swing.JTextField TFRegion;
    private javax.swing.JTextField TFUsername;
    // End of variables declaration//GEN-END:variables
}
