/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hermes.gui;

import com.hermes.common.HUser;
import java.awt.event.MouseAdapter;
import javax.swing.DefaultListModel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author jomartinez
 */
public class MainChatPane extends ChatPane
{

    /**
     * Creates new form MainChatPane
     */
    public MainChatPane()
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        SPSplitter = new javax.swing.JSplitPane();
        SPUsers = new javax.swing.JScrollPane();
        LUsers = new javax.swing.JList();
        SPChat = new javax.swing.JScrollPane();

        SPSplitter.setDividerLocation(976);
        SPSplitter.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentResized(java.awt.event.ComponentEvent evt)
            {
                SPSplitterComponentResized(evt);
            }
        });

        SPUsers.setHorizontalScrollBar(null);

        LUsers.setModel(new DefaultListModel<HUser>());
        LUsers.setFixedCellHeight(58);
        LUsers.setCellRenderer(new UserRenderer());
        LUsers.setBorder(new EmptyBorder(10,10, 10, 10));
        SPUsers.setViewportView(LUsers);

        SPSplitter.setRightComponent(SPUsers);

        SPChat.setViewportView(EPChat);
        SPSplitter.setLeftComponent(SPChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPSplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPSplitter, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SPSplitterComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_SPSplitterComponentResized
    {//GEN-HEADEREND:event_SPSplitterComponentResized
        SPSplitter.setDividerLocation(0.85);
    }//GEN-LAST:event_SPSplitterComponentResized


    public void updateusers()
    {
        LUsers.repaint();
    }
    public void addUser(HUser usr)
    {
        ((DefaultListModel<HUser>)LUsers.getModel()).addElement(usr);
        LUsers.repaint();
    }
    
    public void removeUser(HUser usr)
    {
        ((DefaultListModel<HUser>)LUsers.getModel()).removeElement(usr);
        LUsers.repaint();
    }
    
    public void addMouseClickEvent(MouseAdapter evt)
    {
       LUsers.addMouseListener(evt);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList LUsers;
    private javax.swing.JScrollPane SPChat;
    private javax.swing.JSplitPane SPSplitter;
    private javax.swing.JScrollPane SPUsers;
    // End of variables declaration//GEN-END:variables
}
